# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fin_agent_pb2 as fin__agent__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fin_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FinAgentServiceStub(object):
    """--- 服务接口定义 ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamFinancialData = channel.unary_stream(
                '/finagent.FinAgentService/StreamFinancialData',
                request_serializer=fin__agent__pb2.Empty.SerializeToString,
                response_deserializer=fin__agent__pb2.DataEnvelope.FromString,
                _registered_method=True)
        self.CoordinateTask = channel.stream_stream(
                '/finagent.FinAgentService/CoordinateTask',
                request_serializer=fin__agent__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=fin__agent__pb2.AnalysisResponse.FromString,
                _registered_method=True)
        self.ExecuteTrade = channel.unary_unary(
                '/finagent.FinAgentService/ExecuteTrade',
                request_serializer=fin__agent__pb2.TradeSignal.SerializeToString,
                response_deserializer=fin__agent__pb2.TradeResponse.FromString,
                _registered_method=True)


class FinAgentServiceServicer(object):
    """--- 服务接口定义 ---

    """

    def StreamFinancialData(self, request, context):
        """1. 服务端流：C++ 侧不断推送行情和资讯，Python 侧 Agent 监听
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CoordinateTask(self, request_iterator, context):
        """2. 双向流：Agent 之间的任务分发与反馈协同
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTrade(self, request, context):
        """3. 简单 RPC：下达交易指令
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FinAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamFinancialData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFinancialData,
                    request_deserializer=fin__agent__pb2.Empty.FromString,
                    response_serializer=fin__agent__pb2.DataEnvelope.SerializeToString,
            ),
            'CoordinateTask': grpc.stream_stream_rpc_method_handler(
                    servicer.CoordinateTask,
                    request_deserializer=fin__agent__pb2.AnalysisRequest.FromString,
                    response_serializer=fin__agent__pb2.AnalysisResponse.SerializeToString,
            ),
            'ExecuteTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTrade,
                    request_deserializer=fin__agent__pb2.TradeSignal.FromString,
                    response_serializer=fin__agent__pb2.TradeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'finagent.FinAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('finagent.FinAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FinAgentService(object):
    """--- 服务接口定义 ---

    """

    @staticmethod
    def StreamFinancialData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/finagent.FinAgentService/StreamFinancialData',
            fin__agent__pb2.Empty.SerializeToString,
            fin__agent__pb2.DataEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CoordinateTask(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/finagent.FinAgentService/CoordinateTask',
            fin__agent__pb2.AnalysisRequest.SerializeToString,
            fin__agent__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finagent.FinAgentService/ExecuteTrade',
            fin__agent__pb2.TradeSignal.SerializeToString,
            fin__agent__pb2.TradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
